# Generated by Django 4.1.5 on 2023-02-19 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Proje Başlığı')),
                ('text', models.TextField(max_length=500, verbose_name='Proje Özellikleri')),
                ('text2', models.TextField(max_length=50, verbose_name='Yıllık Geliri')),
                ('text3', models.TextField(max_length=50, verbose_name='Kullanıcı Sayısı')),
                ('text4', models.TextField(max_length=50, verbose_name='Kategorisi')),
                ('text5', models.TextField(max_length=50, verbose_name='Proje Tarihi')),
                ('text6', models.TextField(max_length=50, verbose_name='Kapanış Fiyatı')),
            ],
        ),
    ]
