# Generated by Django 4.1.5 on 2023-02-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.FileField(null=True, upload_to='', verbose_name='Proje Fotoğrafı'),
        ),
    ]
